replicaCount: 1
# $ echo $CI_REGISTRY_IMAGE maia.press:5050/maia/frontend
# $CONTAINER_RELEASE_IMAGE http://localhost:5000/maia/frontend:develop
# $CI_BUILD_REF_NAME develop
# echo $CI_COMMIT_BRANCH develop
# docker pull $IMAGE_TAG develop: Pulling from maia/frontend
#To see deployment progress for your environments, make sure you are deploying to $KUBE_NAMESPACE 
#and annotating with app.gitlab.com/app=$CI_PROJECT_PATH_SLUG and app.gitlab.com/env=$CI_ENVIRONMENT_SLUG.
image:
  repository: __CI_REGISTRY_IMAGE__
  pullPolicy: Always
  tag: __CI_COMMIT_BRANCH__

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
env:
serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 80
  
ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: __HOST_URL__
      paths:
        - path: /
          pathType: ImplementationSpecific     
  tls: 
     - hosts: __CI_COMMIT_REF_SLUG__
       secretName: __CI_COMMIT_REF_SLUG__
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}

certificate:
  name: __CI_COMMIT_REF_SLUG__   
  issuer_name: letsencrypt-test
  email: support@colmena.network 