stages:
  - build    
  - test
  - deploy
  - cleanup
build:   
  stage: build
  script:
   - npm i
   - npm run build
test:
  stage: test
  script:
   - echo sem teste
  needs:
    - build
deploy_prod:
  stage: deploy
  script:
    - echo "Deploy to production server"
  environment:
    name: production
    url: https://maia.press
  needs:
    - build
  when: manual
  only:
    - master
deploy_review:
  stage: deploy
  script:
    - echo "Deploy to review server"
  only:
    - branches
  except:
    - master
