stages:
  - build    
  - test
  - deploy
  - cleanup
build:   
  stage: build
  script:
   - apt update
   - apt -y install curl
   - curl -sL https://deb.nodesource.com/setup_14.x -o nodesource_setup.sh
   - bash nodesource_setup.sh
   - npm i
   - npm run build
test:
  stage: test
  script:
   - npm i --save-dev jest ts-jest
   - npm run test
  needs:
    - build
deploy_prod:
  stage: deploy
  script:
    - echo "Deploy to production server"
  environment:
    name: production
    url: https://maia.press
  needs:
    - build
  when: manual
  only:
    - master
deploy_review:
  stage: deploy
  script:
    - echo "Deploy to review server"
  only:
    - branches
  except:
    - master
