stages:
  - build    
 # - test
 # - deploy
 # - cleanup
cache:
  paths:
#    - node_modules/
    - out
#    - pages
#    - public 
#    - styles
build_dev:
  stage: build
  script:
   - npm i
   - npm run build
  only:
    - branches
  except: 
    - main
build_prod:
  stage: build
  script:
    - echo "fake deploy"
  only:
    - main
 