stages:
  - build    
  - test
 # - deploy
 # - cleanup
#cache:
#  paths:
#    - node_modules/
#    - out
#    - pages
#    - public 
#    - styles
test_all:
  stage: test
  script:
    - npm v

build_dev:
  stage: build
  script:
   - npm i
   - npm run build
  only:
    - branches
  except: 
    - main
  artifacts:
    name: ${CI_PROJECT_NAME}-${CI_BUILD_REF}-${CI_BUILD_NAME}
    paths:
      - out
    expire_in: 10 days
build_prod:
  stage: build
  script:
    - npm i
    - npm run build
  only:
    - main
  artifacts:
    name: ${CI_PROJECT_NAME}-${CI_BUILD_REF}-${CI_BUILD_NAME}
    paths:
      - out
    expire_in: 10 days

 
