variables:
  CONTAINER_IMAGE: maia/frontend:$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: http://localhost:5000/maia/frontend:$CI_BUILD_REF_NAME
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$ 
  HOST_URL: $CI_COMMIT_REF_SLUG.colmena.network

stages:
  #- prepare
  #- build
  #- registry
  - deploy
  #- livetest
  # - cleanup
cache:
  paths:
    - node_modules/
    - out/

# tests:
#   stage: prepare
#   script:
#     - echo "TODO TESTS"
#   only:
#     - branches
#     - tags
#   except:
#    - main


# builder-feature:
#   tags:
#     - docker
#   stage: build
#   script:
#     - cp $ENV_FILE .env
#     - docker build . -t $IMAGE_TAG --no-cache
#   environment:
#     name: feature
#     #name: $CI_BUILD_REF_NAME
#   except:
#    - main
#    - develop
#    - tags
#    - translation

# builder-staging:
#   tags:
#     - docker
#   stage: build
#   script:
#     - cp $ENV_FILE .env
#     - docker build . -t $IMAGE_TAG --no-cache
#   environment:
#     name: staging
#     #name: $CI_BUILD_REF_NAME
#   only:
#     - develop
    

# builder-production:
#   tags:
#     - docker
#   stage: build
#   script:
#     - cp $ENV_FILE .env
#     - docker build . -t $IMAGE_TAG --no-cache
#   environment:
#     name: production
#     #name: $CI_BUILD_REF_NAME
#   only:
#     - main
#     - tags

# register:
#   tags:
#     - docker
#   stage: registry
#   script:
#     - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#     - docker push $IMAGE_TAG


configure_cluster:
  tags:
    - k8
  stage: deploy
  script: 
    - echo $KUBE_NAMESPACE
    - echo $KUBE_CERTIFICATE
    - echo $CI_COMMIT_REF_SLUG
    - echo $CI_ENVIRONMENT_SLUG
    - echo $CI_PROJECT_PATH_SLUG
    - >
       helm upgrade --install --debug $CI_COMMIT_REF_SLUG colmena \
        --set image.tag=$CI_COMMIT_BRANCH \
        --set image.repository=$CI_REGISTRY_IMAGE \
        -f ./chart/env-values.yaml \
        -n $KUBE_NAMESPACE \
        --set serviceAccount.annotations."app\.gilab\.com\/env"=testk8 \
        --set serviceAccount.annotations."app\.gilab\.com\/app"=maia-frontend \
        --set certificate.issuer_name=letsencrypt-$CI_COMMIT_REF_SLUG \
        --set certificate.name=$HOST_URL \
        --set certificate.email=support@colmena.network \
        --set ingress.tls[0].secretName=$HOST_URL,ingress.tls[0].hosts=$HOST_URL \
        --set service.port=80,service.type=ClusteIP \
        --set ingress.hosts[0].host=$HOST_URL,ingress.hosts[1].paths[0].path=/,ingress.hosts[1].paths[0].pathType=ImplementationSpecific \
  environment:
    name: testk8
  only: 
    - k8deploy

#test_all:
#  stage: livetest
#  tags:
#    - lighthouse
#  script:
#    - npm install
#    - npm run build
#    - npm install -g @lhci/cli@0.3.x
#    - lhci autorun --upload.target=temporary-public-storage --collect.settings.chromeFlags="--no-sandbox" || echo "LHCI failed!"
