variables:
  CONTAINER_IMAGE: maia/frontend:$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: http://localhost:5000/maia/frontend:$CI_BUILD_REF_NAME
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$ 
  HOST_URL: $CI_COMMIT_REF_SLUG.colmena.network

stages:
  #- prepare
  #- build
  #- registry
  - deploy
  #- livetest
  # - cleanup
cache:
  paths:
    - node_modules/
    - out/

# tests:
#   stage: prepare
#   script:
#     - echo "TODO TESTS"
#   only:
#     - branches
#     - tags
#   except:
#    - main


# builder-feature:
#   tags:
#     - docker
#   stage: build
#   script:
#     - cp $ENV_FILE .env
#     - docker build . -t $IMAGE_TAG --no-cache
#   environment:
#     name: feature
#     #name: $CI_BUILD_REF_NAME
#   except:
#    - main
#    - develop
#    - tags
#    - translation

# builder-staging:
#   tags:
#     - docker
#   stage: build
#   script:
#     - cp $ENV_FILE .env
#     - docker build . -t $IMAGE_TAG --no-cache
#   environment:
#     name: staging
#     #name: $CI_BUILD_REF_NAME
#   only:
#     - develop
    

# builder-production:
#   tags:
#     - docker
#   stage: build
#   script:
#     - cp $ENV_FILE .env
#     - docker build . -t $IMAGE_TAG --no-cache
#   environment:
#     name: production
#     #name: $CI_BUILD_REF_NAME
#   only:
#     - main
#     - tags

# register:
#   tags:
#     - docker
#   stage: registry
#   script:
#     - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#     - docker push $IMAGE_TAG


configure_cluster:
  tags:
    - k8
  stage: deploy
  script: 
    - echo $KUBE_NAMESPACE
    - echo $KUBE_CERTIFICATE
    - echo $CI_COMMIT_REF_SLUG
    - echo $CI_ENVIRONMENT_SLUG
    - echo $CI_PROJECT_PATH_SLUG
    - >
        helm upgrade --install $CI_COMMIT_REF_SLUG chart
        --set image.tag=$CI_COMMIT_BRANCH
        --set image.repository=$CI_REGISTRY_IMAGE
        --set ingress.hosts.host=$HOST_URL
        --set ingress.tls[0]=hosts=${HOST_URL}
        --set ingress.tls[1]=secretName=${HOST_URL}
        --set ServiceAccount.annotations[0]=app.gitlab.com/app=${CI_PROJECT_PATH_SLUG}
        --set ServiceAccount.annotations[1]=app.gitlab.com/env=${CI_ENVIRONMENT_SLUG}
        --set ingress.annotations[0]=app.gitlab.com/app=${CI_PROJECT_PATH_SLUG}
        --set ingress.annotations[1]=app.gitlab.com/env=${CI_ENVIRONMENT_SLUG}
        --set certificate.name=$CI_COMMIT_REF_SLUG
        --set certificate.issuer_name=letsencrypt-$CI_COMMIT_REF_SLUG
        --set certificate.email=support@colmena.network
        -n $KUBE_NAMESPACE
  environment:
    name: testk8
  only: 
    - k8deploy

#test_all:
#  stage: livetest
#  tags:
#    - lighthouse
#  script:
#    - npm install
#    - npm run build
#    - npm install -g @lhci/cli@0.3.x
#    - lhci autorun --upload.target=temporary-public-storage --collect.settings.chromeFlags="--no-sandbox" || echo "LHCI failed!"
