stages:
  - build    
  - test
  - deploy
  - cleanup
#cache:
#  paths:
#    - node_modules/
#    - out
#    - pages
#    - public 
#    - styles
build_dev:
  stage: build
  script:
   - npm i
   - npm run build
  only:
    - branches
  except:
    - main
#deploy_prod:
#  stage: deploy
#  script:
#    - echo "deploy"
 
