apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.name  }}
  labels:
    {{ .Values.application.name| nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{ .Values.application.name . | nindent 4 }}
