apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
   name: {{ .Values.certificate.issuer_name }}
   namespace: 
spec:
  acme:
    email: {{.Values.certificate.email}}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: {{.Values.certificate.issuer_name}}
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
    - http01:
        ingress:
          class: nginx