export const USER_UPDATE = "USER_UPDATE";
export const USER_INFO_UPDATE = "USER_INFO_UPDATE";
export const MEDIA_INFO_UPDATE = "MEDIA_INFO_UPDATE";
export const SET_INVITATION_TOKEN = "SET_INVITATION_TOKEN";

export const RECORDING_INSERT = "RECORDING_INSERT";
export const RECORDING_UPDATE = "RECORDING_UPDATE";
export const CLEAR_RECORDINGS = "CLEAR_RECORDINGS";
export const SET_ACTIVE_RECORDING_STATE = "SET_ACTIVE_RECORDING_STATE";
export const SET_ALLOW_BROWSER_RECORDING = "SET_ALLOW_BROWSER_RECORDING";
export const SET_PLAYING_AUDIO_PREVIEW = "SET_PLAYING_AUDIO_PREVIEW";

export const SET_CHANGED_LANGUAGE = "SET_CHANGED_LANGUAGE";

export const SET_LIBRARY_FILES = "SET_LIBRARY_FILES";
export const ADD_LIBRARY_FILE = "ADD_LIBRARY_FILE";
export const EDIT_LIBRARY_FILE = "EDIT_LIBRARY_FILE";
export const REMOVE_LIBRARY_FILE = "REMOVE_LIBRARY_FILE";
export const SET_LIBRARY_PATH_EXISTS = "SET_LIBRARY_PATH_EXISTS";
export const SET_LIBRARY_PATH = "SET_LIBRARY_PATH";
export const CURRENT_AUDIO_PLAYING = "CURRENT_AUDIO_PLAYING";

export const SET_HONEYCOMBS = "SET_HONEYCOMBS";
export const ADD_HONEYCOMB = "ADD_HONEYCOMB";
export const EDIT_HONEYCOMB = "EDIT_HONEYCOMB";
export const REMOVE_HONEYCOMB = "REMOVE_HONEYCOMB";
export const SET_CHAT_LIST = "SET_CHAT_LIST";
export const ADD_CHAT_MESSAGE = "ADD_CHAT_MESSAGE";
export const ADD_TOKEN_CHAT_CLEAR_MESSAGES = "ADD_TOKEN_CHAT_CLEAR_MESSAGES";
export const RELOAD_CHAT_LOCAL_MESSAGES = "RELOAD_CHAT_LOCAL_MESSAGES";

export const SET_CURSOR_SELECTED = "SET_CURSOR_SELECTED";
