export const USER_UPDATE = "USER_UPDATE";
export const SET_INVITATION_TOKEN = "SET_INVITATION_TOKEN";

export const RECORDING_INSERT = "RECORDING_INSERT";
export const RECORDING_UPDATE = "RECORDING_UPDATE";
export const CLEAR_RECORDINGS = "CLEAR_RECORDINGS";
export const SET_ACTIVE_RECORDING_STATE = "SET_ACTIVE_RECORDING_STATE";
export const SET_ALLOW_BROWSER_RECORDING = "SET_ALLOW_BROWSER_RECORDING";
